/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import entidades.Auditoria;
import dao.AuditoriaDAO;
import apoio.templateTitulos;

/**
 *
 * @author Maryhana Kuhn
 */
public class IfrConfiguracoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrConfiguracoes
     */
    public IfrConfiguracoes() {
        initComponents();
        System.out.println("vai começar");
        //Auditoria audi = new Auditoria();
        AuditoriaDAO audDAO = new AuditoriaDAO();
        //IfrConfiguracoes ifrConfig = new IfrConfiguracoes();

        audDAO.consultaEstado(getChkAtivaAuditoria().isSelected());
        //audi.getAtivaAuditoria();
        //audDAO.

        System.out.println("pegou do banco");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkAtivaAuditoria = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Configurações");

        chkAtivaAuditoria.setSelected(true);
        chkAtivaAuditoria.setText("Ativa auditoria");
        chkAtivaAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAtivaAuditoriaActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkAtivaAuditoria)
                .addContainerGap(293, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(chkAtivaAuditoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        controleAtualizacao();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void chkAtivaAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAtivaAuditoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAtivaAuditoriaActionPerformed
//    public boolean AtivaAuditoria;
//
//    public void salvarAud(Auditoria Aud) {
//        IfrConfiguracoes ifrConfig = new IfrConfiguracoes();
//        Auditoria aud = new Auditoria();
//        aud.setAtivaAuditoria(chkAtivaAuditoria.isSelected());
//    }

    public boolean chamaChkAtivaAuditoria() {
        if (getChkAtivaAuditoria().isSelected()) {
            return true;
        }
        return false;
    }

    public boolean verificaEstado() {
        //boolean chkAtivaAuditoriaB;
        Auditoria audi = new Auditoria();
        AuditoriaDAO audDAO = new AuditoriaDAO();
        IfrConfiguracoes ifrConfig = new IfrConfiguracoes();
//        //ifrConfig.setChkAtivaAuditoria(chkAtivaAuditoria.equals(ifrConfig.get));
//        if (chkAtivaAuditoria.isSelected()) {
//            audDAO.consultaEstado(true);
//            audDAO.salvar(audi);
//            System.out.println("ativou auditoria");
//        } else {
//            audDAO.consultaEstado(false);
//            audDAO.salvar(audi);
//            System.out.println("desativou auditoria");
//}

        if(audi.getAtivaauditoria()){
            audi.setAtivaauditoria(true);
            audDAO.salvar(audi);
            System.out.println("ativou auditoria");
            return true;
        }else{
            audi.setAtivaauditoria(false);
            audDAO.salvar(audi);
            System.out.println("desativou auditoria");
        }
        return false;
    }

    private void controleAtualizacao() {
        Auditoria aud = new Auditoria();
        AuditoriaDAO audDAO = new AuditoriaDAO();
        aud.setAtivaauditoria(getChkAtivaAuditoria().isSelected());
        if (audDAO.salvar(aud)) {
            JOptionPane.showMessageDialog(null, templateTitulos.getMsgOpSalvo());
        } else {
            JOptionPane.showMessageDialog(null, templateTitulos.getMsgOperacaoErro());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkAtivaAuditoria;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the chkAtivaAuditoria
     */
    public javax.swing.JCheckBox getChkAtivaAuditoria() {
        return chkAtivaAuditoria;
    }

    /**
     * @param chkAtivaAuditoria the chkAtivaAuditoria to set
     */
    public void setChkAtivaAuditoria(javax.swing.JCheckBox chkAtivaAuditoria) {
        this.chkAtivaAuditoria = chkAtivaAuditoria;
    }

//    public boolean isAtivaAuditoria() {
//        return AtivaAuditoria;
//    }
//
//    public void setAtivaAuditoria(boolean AtivaAuditoria) {
//        this.AtivaAuditoria = AtivaAuditoria;
//    }
}
